name: "Setup Testify Environment (Container)"
description: "Sets up Python dependencies inside a Playwright container"
runs:
  using: "composite"
  steps:
    - name: Verify System Python
      shell: bash
      run: |
        python3 --version || (apt-get update && apt-get install -y python3 python3-pip)

    - name: Install Python dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
