name: "Setup Testify Environment"
description: "Sets up Python, dependencies, and Playwright browsers with caching"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get Playwright Version
      shell: bash
      id: playwright-version
      run: echo "VERSION=$(python -c 'import playwright; print(playwright.__version__)')" >> $GITHUB_OUTPUT

    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.VERSION }}

    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: python -m playwright install chromium

    - name: Install Playwright System Deps
      shell: bash
      run: python -m playwright install-deps
